// <auto-generated />
using System;
using KubiczPlace.Finances.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KubiczPlace.Finances.Migrations.FinanceDb
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260206001856_InitialFinance")]
    partial class InitialFinance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("KubiczPlace.Finances.Shared.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 50m,
                            Name = "Strzyżenie męskie"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 80m,
                            Name = "Strzyżenie damskie"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 30m,
                            Name = "Broda"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 150m,
                            Name = "Koloryzacja"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 70m,
                            Name = "Strzyżenie + Broda"
                        });
                });

            modelBuilder.Entity("KubiczPlace.Finances.Shared.ServiceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommissionPercentageApplied")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("DatePerformed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tips")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("WorkerId");

                    b.ToTable("ServiceRecords");
                });

            modelBuilder.Entity("KubiczPlace.Finances.Shared.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultCommissionPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultCommissionPercentage = 50m,
                            Name = "Jan Kowalski"
                        },
                        new
                        {
                            Id = 2,
                            DefaultCommissionPercentage = 45m,
                            Name = "Anna Nowak"
                        },
                        new
                        {
                            Id = 3,
                            DefaultCommissionPercentage = 55m,
                            Name = "Piotr Wiśniewski"
                        });
                });

            modelBuilder.Entity("KubiczPlace.Finances.Shared.ServiceRecord", b =>
                {
                    b.HasOne("KubiczPlace.Finances.Shared.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KubiczPlace.Finances.Shared.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Worker");
                });
#pragma warning restore 612, 618
        }
    }
}
